### ISSUE TITLE
Make shortcuts more consistent with other bundles

### ISSUE THREAD

**Issue by carols10cents** [carols10cents/rust.tmbundle#13]
See discussion on https://github.com/carols10cents/rust.tmbundle/pull/10 and https://github.com/textmate/textmate/pull/1305.

Once the textmate PR is merged and released:
- [x] Use the scope `attr.project.cargo` on the Cargo commands
- [x] Change the shortcuts to be as follows:
<table>
  <tr>
    <th>Without Cargo.toml</th>
    <th>With Cargo.toml</th>
    <th>Shortcut:</th>
  </tr>
  <tr>
    <td>Compile current file</td>
    <td>Cargo build current project</td>
    <td>cmd + b</td>
  </tr>
  <tr>
    <td>Compile current file with tests</td>
    <td>(no equivalent)</td>
    <td>cmd + shift + b</td>
  </tr>
  <tr>
    <td>Compile and run current file</td>
    <td>Cargo run current project</td>
    <td>cmd + r</td>
  </tr>
  <tr>
    <td>Compile with tests and run the tests</td>
    <td>Cargo test current project</td>
    <td>cmd + shift + r</td>
  </tr>
</table>
- [x] Update the README documenting these shortcuts

**Comment by infininight** [comment]
`attr.project.cargo` is now available in the nightly builds, will post again when this moves to the normal release.

**Comment by carols10cents** [comment]
Awesome, thank you! Working on this today :)
