### ISSUE TITLE
Auto inserted curly braces should indent when enter key pressed

### ISSUE THREAD

**Issue by JavaNut13** [carols10cents/rust.tmbundle#17]
When a pair of curly braces is auto inserted and the enter key is pressed (i.e. when you're defining a function) the closing brace should be pushed down a line and the caret indented.

The current behaviour is like this: (Where the pipe is the caret)

    fn main() {|}
Enter key pressed..

    fn main() {
    |}

Languages in TextMate that use curly braces ([Swift](https://github.com/textmate/swift.tmbundle/blob/master/Syntaxes/Swift.tmLanguage), [Java](https://github.com/textmate/java.tmbundle), [Ruby](https://github.com/textmate/ruby.tmbundle/blob/master/Preferences/Block%20typing%20pairs.plist)) have this behaviour, which is more streamlined and encourages good formatting:

    fn main() {|}

Enter key pressed..

    fn main() {
        |
    }

> (I had a look the bundles for those other languages and - with my limited bundle knowledge - couldn't see how this was done.)

**Comment by infininight** [comment]
Explained here:

http://lists.macromates.com/textmate/2012-January/034108.html

**Comment by carols10cents** [comment]
Looking into this now, thank you for the report @JavaNut13 and the additional info @infininight !!!!

**Comment by carols10cents** [comment]
Should be fixed in master now, @JavaNut13 !!! Thank you!!!!

![textmate-bundle-bugfix](https://cloud.githubusercontent.com/assets/193874/12538095/4826c1fa-c29e-11e5-919b-d267d2fe1f56.gif)
