### ISSUE TITLE
< causes highlighting failure

### ISSUE THREAD

**Issue by taralx** [carols10cents/rust.tmbundle#21]
```rust
fn main() {
	let a = 1;
	if a < 1 {}
	let b = 2;
}
```

Stops highlighting after the if due to use of <.

**Comment by carols10cents** [comment]
Hmm, I thought I fixed that in https://github.com/carols10cents/rust.tmbundle/commit/b32d2cbe78a5bf76fcea024f32f7ea5b3248c681. @infininight, has that commit been pushed out? If not, could you please? Thanks!!

**Comment by infininight** [comment]
@taralx The commit the @carols10cents mentioned hadn't been deployed to the updater. It has now, you bundle should update within a few hours with the fix.

@carols10cents I've starred this bundle so I quasi-monitor the issues to see when issues are closed to push an update but it doesn't notify me of commits. Just poke me via email/twitter/irc and I can push out updates whenever, just takes a second. Sorry if I missed you poking me back in March. :)

**Comment by taralx** [comment]
Thank you both!
