### ISSUE TITLE
"Compile" doesn't work due to incorrect cwd

### ISSUE THREAD

**Issue by snej** [carols10cents/rust.tmbundle#4]
I just installed the bundle, opened a Rust file, and chose the "Compile" command from the bundle menu. Immediate error alert:

    Failure running 'Compile':
    error: could not write output to hello.0.o: Permission denied

The cause turns out to be that `rustc` writes intermediate files, as well as the executable, to the current working directory, _not_ to the parent directory of the source file. And when a TextMate script runs, the CWD seems to be bogus; in my case it turns out to be `/`.

I'm not sure how this could be working for anyone else. Did TextMate's behavior just change? Or rustc's? I've got the latest of both — TextMate 2.0-beta.7.1, and rustc 1.0.0-beta.2 (e9080ec39 2015-04-16). My OS version is 10.10.4 (14E7f).

**Comment by infininight** [comment]
This was changed in TextMate version 2013-05-17 (a9423), from the release notes:

> The working directory of the command being executed is unspecified except for drop commands (where it is the parent of the current file). We have never documented what the working directory is set to, and if you need it to be set to something specific (e.g. TM_PROJECT_DIRECTORY) then you should set it yourself.

**Comment by carols10cents** [comment]
Awesome, thank you!

**Comment by carols10cents** [comment]
I think I've fixed this, please try it out and let me know!!
